learning_site/courses/urls.py
from django.conf.urls import url

from . import views



urlpatterns = [
    url(r'^$', views.course_list),
    url(r'(?P<pk>\d+)/$', views.course_detail),
]

learning_site/learning_site/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from . import views

urlpatterns = [
    url(r'^courses/', include('courses.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.hello_world),

]
urlpatterns += staticfiles_urlpatterns()

learning_site/courses/models.py
from django.db import models



class Course(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length=255)
    description = models.TextField()

    def __str__(self):
        return self.title

class Step(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    order = models.IntegerField(default=0)
    course = models.ForeignKey(Course)

    class Meta:
        ordering = ['order', ]


    def __str__(self):
        return self.title



# c = Course()
# c.title = "Python Basics"
# c.description = "Learn the basics of Python"
# c.save()
#
# Course(title="Python Collections", description="Learn about list, dict, and tuple").save()
#
# Course.objects.create(title="Object-Oriented Python", description = "Learn about Python's classes")
#

learning_site/courses/views.py
from django.shortcuts import get_object_or_404, render

from .models import Course


def course_list(request):
    courses = Course.objects.all()
    return render(request, 'courses/course_list.html', {'courses': courses})


def course_detail(request, pk):
    course = get_object_or_404(Course, pk=pk)
    return render(request, 'courses/course_detail.html', {'course': course})

learning_site/learning_site/views.py
from django.shortcuts import render


def hello_world(request):
    return render(request, 'home.html')

learning_site/courses/templates/courses/course_detail.html
{% extends "layout.html" %}

{% block title %}{{ course.title }}{% endblock %}

{% block content %}
<article>
    <h2>{{ course.title }}</h2>
    {{ course.description }}

    <section>
        {% for step in course.step_set.all %}
            <h3>{{ step.title }}</h3>
        {{ step.description }}
        {% endfor %}
    </section>
</article>

{% endblock %}

learning_site/courses/templates/courses/course_list.html
{% for course in courses %}
<h2>{{ course.title }}</h2>
{{ course.description }}


{% endfor %}

learning_site/templates/home.html
{% extends "layout.html" %}


{% block title %}Well hello there!{% endblock %}


{% block content %}

<h1>Welcome!</h1>

{% endblock %}

learning_site/templates/layout.html
{% load static from staticfiles %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/layout.css' %}">
</head>
<body>
<div class="site-container">
    {% block content %}
    {% endblock %}
</div>
</body>
</html>